### ISSUE TITLE
Manufacturing defects on the new USB-C receptacle

### ISSUE THREAD

**Issue by FHeilmann** [alvarop/usb_c_cable_tester#16]
Hi, thank you for sharing this board!

Unfortunately JLCPCB seems to have issues assembling the new USB-C receptacle. I've ordered 5 assembled PCBs and while the USB2.0 and even the 3.0 A-to-C works ok on 3 or 4 of them, pretty much all of them have issues with the 3.0 C-to-C cable testing.

With a known good USB-3 C-to-C cable, each board shows a different combination of LEDs, on some, even the basic pins such as D+ and D- stay dark, which leads me to believe that the assembly of the Type-C receptacles is faulty.

I've put in a support request with them, let's see how it goes.

edit: Just read the note on the 2.1 pre-release. D'oh. Well thats what I get for not reading everything :D

**Comment by alvarop** [comment]
Hey! Yeah, it was a bummer. I think it would work better with a 0.8mm PCB.
I still need to do an order with that one and see if it helps.
I was able to "fix" many of them manually with a soldering iron but it's a pain...

The previous connector that was SMT only was great, but it shorts all the ground pins together with the shield :(

**Comment by alvarop** [comment]
I changed to use 0.8mm PCB's (instead of 1.6mm) and had MUCH better results. 95% yield :D
![IMG_9716](https://github.com/alvarop/usb_c_cable_tester/assets/744129/cb0138dc-7add-4e0e-97db-a8a1df190a00)

1/20 boards had some solder bridges on the USB-C connector, but it was easy to fix.
![IMG_9716](https://github.com/alvarop/usb_c_cable_tester/assets/744129/55a54124-5bce-47ac-bece-5b75562eb38a)

Not all of the boards had the soldermask missing between the pins though. Might have to slightly change the footprint to improve the chances of the mask being there.

![IMG_9728](https://github.com/alvarop/usb_c_cable_tester/assets/744129/68430011-04c8-41bd-ad07-9d5c6884ece0)

The through hole pins had much better soldering on them:
![IMG_9723](https://github.com/alvarop/usb_c_cable_tester/assets/744129/cbae951a-455e-44ec-9370-9412abefc686)
